// This file is auto-generated by @hey-api/openapi-ts

import { type Client, type ClientMeta, formDataBodySerializer, type Options as Options2, type RequestResult, type TDataShape } from './client';
import { client } from './client.gen';
import type { CreateFolderData, CreateFolderErrors, CreateFolderResponses, DeleteFileData, DeleteFileErrors, DeleteFileResponses, DownloadFileData, DownloadFileErrors, DownloadFileResponses, GetConfigData, GetConfigErrors, GetConfigResponses, GetHealthData, GetHealthErrors, GetHealthResponses, ListFilesData, ListFilesErrors, ListFilesResponses, MoveFileData, MoveFileErrors, MoveFileResponses, RestartData, RestartErrors, RestartResponses, SaveConfigData, SaveConfigErrors, SaveConfigResponses, UploadFilesData, UploadFilesErrors, UploadFilesResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Get the settings
 */
export const getConfig = <ThrowOnError extends boolean = false>(options?: Options<GetConfigData, ThrowOnError>): RequestResult<GetConfigResponses, GetConfigErrors, ThrowOnError> => (options?.client ?? client).get<GetConfigResponses, GetConfigErrors, ThrowOnError>({ url: '/api/config', ...options });

/**
 * Save settings to the config file
 *
 * The saved settings apply after a restart.
 */
export const saveConfig = <ThrowOnError extends boolean = false>(options: Options<SaveConfigData, ThrowOnError>): RequestResult<SaveConfigResponses, SaveConfigErrors, ThrowOnError> => (options.client ?? client).put<SaveConfigResponses, SaveConfigErrors, ThrowOnError>({
  url: '/api/config',
  ...options,
  headers: {
    'Content-Type': 'application/json',
    ...options.headers
  }
});

/**
 * Delete a file or folder with its content
 */
export const deleteFile = <ThrowOnError extends boolean = false>(options?: Options<DeleteFileData, ThrowOnError>): RequestResult<DeleteFileResponses, DeleteFileErrors, ThrowOnError> => (options?.client ?? client).delete<DeleteFileResponses, DeleteFileErrors, ThrowOnError>({ url: '/api/files', ...options });

/**
 * List a folder
 */
export const listFiles = <ThrowOnError extends boolean = false>(options?: Options<ListFilesData, ThrowOnError>): RequestResult<ListFilesResponses, ListFilesErrors, ThrowOnError> => (options?.client ?? client).get<ListFilesResponses, ListFilesErrors, ThrowOnError>({ url: '/api/files', ...options });

/**
 * Download a file
 *
 * Supports range requests.
 */
export const downloadFile = <ThrowOnError extends boolean = false>(options?: Options<DownloadFileData, ThrowOnError>): RequestResult<DownloadFileResponses, DownloadFileErrors, ThrowOnError> => (options?.client ?? client).get<DownloadFileResponses, DownloadFileErrors, ThrowOnError>({ url: '/api/files/download', ...options });

/**
 * Create a folder
 */
export const createFolder = <ThrowOnError extends boolean = false>(options: Options<CreateFolderData, ThrowOnError>): RequestResult<CreateFolderResponses, CreateFolderErrors, ThrowOnError> => (options.client ?? client).post<CreateFolderResponses, CreateFolderErrors, ThrowOnError>({
  url: '/api/files/mkdir',
  ...options,
  headers: {
    'Content-Type': 'application/json',
    ...options.headers
  }
});

/**
 * Rename or move a file or folder
 */
export const moveFile = <ThrowOnError extends boolean = false>(options: Options<MoveFileData, ThrowOnError>): RequestResult<MoveFileResponses, MoveFileErrors, ThrowOnError> => (options.client ?? client).post<MoveFileResponses, MoveFileErrors, ThrowOnError>({
  url: '/api/files/move',
  ...options,
  headers: {
    'Content-Type': 'application/json',
    ...options.headers
  }
});

/**
 * Upload files into a folder
 */
export const uploadFiles = <ThrowOnError extends boolean = false>(options: Options<UploadFilesData, ThrowOnError>): RequestResult<UploadFilesResponses, UploadFilesErrors, ThrowOnError> => (options.client ?? client).post<UploadFilesResponses, UploadFilesErrors, ThrowOnError>({
  ...formDataBodySerializer,
  url: '/api/files/upload',
  ...options,
  headers: {
    'Content-Type': null,
    ...options.headers
  }
});

/**
 * Check that the server is up
 */
export const getHealth = <ThrowOnError extends boolean = false>(options?: Options<GetHealthData, ThrowOnError>): RequestResult<GetHealthResponses, GetHealthErrors, ThrowOnError> => (options?.client ?? client).get<GetHealthResponses, GetHealthErrors, ThrowOnError>({ url: '/api/health', ...options });

/**
 * Restart the server to apply saved settings
 */
export const restart = <ThrowOnError extends boolean = false>(options?: Options<RestartData, ThrowOnError>): RequestResult<RestartResponses, RestartErrors, ThrowOnError> => (options?.client ?? client).post<RestartResponses, RestartErrors, ThrowOnError>({ url: '/api/restart', ...options });
