// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://openapi.json` | (string & {});
};

export type Config = {
  /**
   * Path of the config file.
   */
  file: string;
  /**
   * Saved settings wait for a restart to apply.
   */
  restartPending: boolean;
  settings: Array<Setting>;
};

export type ErrorDetail = {
  /**
   * Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id'
   */
  location?: string;
  /**
   * Error message text
   */
  message?: string;
  /**
   * The value at the given location
   */
  value?: unknown;
};

export type ErrorModel = {
  /**
   * A human-readable explanation specific to this occurrence of the problem.
   */
  detail?: string;
  /**
   * Optional list of individual error details
   */
  errors?: Array<ErrorDetail> | null;
  /**
   * A URI reference that identifies the specific occurrence of the problem.
   */
  instance?: string;
  /**
   * HTTP status code
   */
  status?: number;
  /**
   * A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
   */
  title?: string;
  /**
   * A URI reference to human-readable documentation for the error.
   */
  type?: string;
};

export type FileEntry = {
  isDir: boolean;
  kind: 'folder' | 'video' | 'subtitle' | 'other';
  modTime: string;
  name: string;
  /**
   * Slash-separated path relative to the media folder.
   */
  path: string;
  size: number;
};

export type Health = {
  ok: boolean;
  startedAt: string;
};

export type Listing = {
  entries: Array<FileEntry>;
  /**
   * Path of the folder, "." for the media folder itself.
   */
  path: string;
};

export type MkdirRequest = {
  /**
   * Path of the new folder.
   */
  path: string;
};

export type MoveRequest = {
  from: string;
  to: string;
};

export type Setting = {
  /**
   * Value without the config file.
   */
  default: string;
  env: string;
  /**
   * Value in the config file, if set there.
   */
  fileValue?: string;
  /**
   * Set by a command line flag or environment variable, so not editable.
   */
  locked: boolean;
  name: string;
  /**
   * Allowed values of an enum setting.
   */
  options?: Array<string>;
  source: 'flag' | 'env' | 'file' | 'default';
  type: 'string' | 'int' | 'bool' | 'enum' | 'list';
  usage: string;
  /**
   * Value of the running server.
   */
  value: string;
};

export type Uploaded = {
  files: Array<FileEntry>;
};

export type GetConfigData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/config';
};

export type GetConfigErrors = {
  /**
   * Error
   */
  default: ErrorModel;
};

export type GetConfigError = GetConfigErrors[keyof GetConfigErrors];

export type GetConfigResponses = {
  /**
   * OK
   */
  200: Config;
};

export type GetConfigResponse = GetConfigResponses[keyof GetConfigResponses];

export type SaveConfigData = {
  /**
   * Setting names mapped to new values; null removes a setting from the config file (back to default).
   */
  body: {
    [key: string]: string | null;
  };
  path?: never;
  query?: never;
  url: '/api/config';
};

export type SaveConfigErrors = {
  /**
   * Bad Request
   */
  400: ErrorModel;
  /**
   * Conflict
   */
  409: ErrorModel;
  /**
   * Unprocessable Entity
   */
  422: ErrorModel;
  /**
   * Internal Server Error
   */
  500: ErrorModel;
};

export type SaveConfigError = SaveConfigErrors[keyof SaveConfigErrors];

export type SaveConfigResponses = {
  /**
   * OK
   */
  200: Config;
};

export type SaveConfigResponse = SaveConfigResponses[keyof SaveConfigResponses];

export type DeleteFileData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Slash-separated path relative to the media folder; empty for the media folder itself.
     */
    path?: string;
  };
  url: '/api/files';
};

export type DeleteFileErrors = {
  /**
   * Bad Request
   */
  400: ErrorModel;
  /**
   * Not Found
   */
  404: ErrorModel;
  /**
   * Unprocessable Entity
   */
  422: ErrorModel;
  /**
   * Internal Server Error
   */
  500: ErrorModel;
};

export type DeleteFileError = DeleteFileErrors[keyof DeleteFileErrors];

export type DeleteFileResponses = {
  /**
   * No Content
   */
  204: void;
};

export type DeleteFileResponse = DeleteFileResponses[keyof DeleteFileResponses];

export type ListFilesData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Slash-separated path relative to the media folder; empty for the media folder itself.
     */
    path?: string;
  };
  url: '/api/files';
};

export type ListFilesErrors = {
  /**
   * Bad Request
   */
  400: ErrorModel;
  /**
   * Not Found
   */
  404: ErrorModel;
  /**
   * Unprocessable Entity
   */
  422: ErrorModel;
  /**
   * Internal Server Error
   */
  500: ErrorModel;
};

export type ListFilesError = ListFilesErrors[keyof ListFilesErrors];

export type ListFilesResponses = {
  /**
   * OK
   */
  200: Listing;
};

export type ListFilesResponse = ListFilesResponses[keyof ListFilesResponses];

export type DownloadFileData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Slash-separated path relative to the media folder; empty for the media folder itself.
     */
    path?: string;
  };
  url: '/api/files/download';
};

export type DownloadFileErrors = {
  /**
   * Bad Request
   */
  400: ErrorModel;
  /**
   * Not Found
   */
  404: ErrorModel;
  /**
   * Unprocessable Entity
   */
  422: ErrorModel;
  /**
   * Internal Server Error
   */
  500: ErrorModel;
};

export type DownloadFileError = DownloadFileErrors[keyof DownloadFileErrors];

export type DownloadFileResponses = {
  /**
   * The file content.
   */
  200: Blob | File;
};

export type DownloadFileResponse = DownloadFileResponses[keyof DownloadFileResponses];

export type CreateFolderData = {
  body: MkdirRequest;
  path?: never;
  query?: never;
  url: '/api/files/mkdir';
};

export type CreateFolderErrors = {
  /**
   * Bad Request
   */
  400: ErrorModel;
  /**
   * Not Found
   */
  404: ErrorModel;
  /**
   * Conflict
   */
  409: ErrorModel;
  /**
   * Unprocessable Entity
   */
  422: ErrorModel;
  /**
   * Internal Server Error
   */
  500: ErrorModel;
};

export type CreateFolderError = CreateFolderErrors[keyof CreateFolderErrors];

export type CreateFolderResponses = {
  /**
   * Created
   */
  201: FileEntry;
};

export type CreateFolderResponse = CreateFolderResponses[keyof CreateFolderResponses];

export type MoveFileData = {
  body: MoveRequest;
  path?: never;
  query?: never;
  url: '/api/files/move';
};

export type MoveFileErrors = {
  /**
   * Bad Request
   */
  400: ErrorModel;
  /**
   * Not Found
   */
  404: ErrorModel;
  /**
   * Conflict
   */
  409: ErrorModel;
  /**
   * Unprocessable Entity
   */
  422: ErrorModel;
  /**
   * Internal Server Error
   */
  500: ErrorModel;
};

export type MoveFileError = MoveFileErrors[keyof MoveFileErrors];

export type MoveFileResponses = {
  /**
   * OK
   */
  200: FileEntry;
};

export type MoveFileResponse = MoveFileResponses[keyof MoveFileResponses];

export type UploadFilesData = {
  body: {
    file: Array<Blob | File>;
  };
  path?: never;
  query?: {
    /**
     * Folder to upload into; empty for the media folder itself.
     */
    path?: string;
    /**
     * Replace existing files.
     */
    overwrite?: boolean;
  };
  url: '/api/files/upload';
};

export type UploadFilesErrors = {
  /**
   * Bad Request
   */
  400: ErrorModel;
  /**
   * Not Found
   */
  404: ErrorModel;
  /**
   * Conflict
   */
  409: ErrorModel;
  /**
   * Unprocessable Entity
   */
  422: ErrorModel;
  /**
   * Internal Server Error
   */
  500: ErrorModel;
};

export type UploadFilesError = UploadFilesErrors[keyof UploadFilesErrors];

export type UploadFilesResponses = {
  /**
   * Created
   */
  201: Uploaded;
};

export type UploadFilesResponse = UploadFilesResponses[keyof UploadFilesResponses];

export type GetHealthData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/health';
};

export type GetHealthErrors = {
  /**
   * Error
   */
  default: ErrorModel;
};

export type GetHealthError = GetHealthErrors[keyof GetHealthErrors];

export type GetHealthResponses = {
  /**
   * OK
   */
  200: Health;
};

export type GetHealthResponse = GetHealthResponses[keyof GetHealthResponses];

export type RestartData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/restart';
};

export type RestartErrors = {
  /**
   * Error
   */
  default: ErrorModel;
};

export type RestartError = RestartErrors[keyof RestartErrors];

export type RestartResponses = {
  /**
   * Accepted
   */
  202: unknown;
};
